import { useState } from 'react'
import type { Brief } from '../types/brief'
import type { ToastType } from './Toast'
import { exportAsPDF } from '../lib/pdfExport'

interface Props {
  brief: Brief
  eventName: string
  onToast?: (text: string, type?: ToastType) => void
}

function formatBrief(brief: Brief, eventName: string): string {
  const { theme, palette, copy, sponsor_deck, logistics_notes } = brief
  return `CREATIVE BRIEF — ${eventName.toUpperCase()}
${'='.repeat(50)}

THEME CONCEPT
${theme.concept}
Moodboard: ${theme.moodboard_keywords.join(' · ')}

COLOR PALETTE
Primary:   ${palette.primary}
Secondary: ${palette.secondary}
Accent:    ${palette.accent}
${palette.rationale}

COPY & MESSAGING
Tagline:     "${copy.tagline}"
Headline:    ${copy.headline}
Body Angle:  ${copy.body_angle}

SPONSOR DECK
${sponsor_deck.value_proposition}
Audience: ${sponsor_deck.audience_snapshot}
Tiers: ${sponsor_deck.tier_names.join(' | ')}

LOGISTICS NOTES
Venue Type: ${logistics_notes.suggested_venue_type}
Production: ${logistics_notes.key_production_elements.join(', ')}
Watch Out: ${logistics_notes.watch_out}

${'—'.repeat(50)}
Generated by BobTheBriefr`
}

export function ExportButton({ brief, eventName, onToast }: Props) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(formatBrief(brief, eventName))
      setCopied(true)
      onToast?.('Brief copied to clipboard', 'success')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      const textarea = document.createElement('textarea')
      textarea.value = formatBrief(brief, eventName)
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      onToast?.('Brief copied to clipboard', 'success')
      setTimeout(() => setCopied(false), 2000)
    }
  }

  function handlePdf() {
    const result = exportAsPDF(brief, eventName)
    if (result === 'blocked') {
      onToast?.('Pop-up blocked — allow pop-ups to export PDF', 'error')
    } else if (result === 'error') {
      onToast?.('PDF export failed. Try again.', 'error')
    } else {
      onToast?.(`Print dialog opened — choose "Save as PDF"`, 'success')
    }
  }

  return (
    <div className="export-group">
      <button type="button" className="btn-export" onClick={handleCopy}>
        {copied ? '✓ Copied!' : '⎘ Copy Brief'}
      </button>
      <button type="button" className="btn-export" onClick={handlePdf}>
        ↓ Export PDF
      </button>
    </div>
  )
}
